export type Variant = {
  id: string;
  articleNumber: string;
  name: string;
  series: string;
  category: string;
  surface: string;
  finish: string;
  pattern: string;
  color: string;
  swatch: string;
  descriptor: string;
  characteristics: string[];
  images: string[];
};

export const variants: Variant[] = [
  // ─── BLACK SERIES ────────────────────────────────────────────────
  {
    id: "bs-01",
    articleNumber: "SL-BS-01",
    name: "Black Smooth",
    series: "Black Series",
    category: "Smooth",
    surface: "Smooth",
    finish: "Matte",
    pattern: "Plain",
    color: "Black",
    swatch: "#111111",
    descriptor: "Ultra-flat surface, zero visible grain.",
    characteristics: [
      "Uniform flat surface texture",
      "Low-reflectivity matte finish",
      "Consistent thickness across roll",
      "Suitable for seat surfaces and door panels",
      "Material samples available upon request",
    ],
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "bs-02",
    articleNumber: "SL-BS-02",
    name: "Black Fine Grain",
    series: "Black Series",
    category: "Grain",
    surface: "Embossed",
    finish: "Matte",
    pattern: "Fine Grain",
    color: "Black",
    swatch: "#1A1A1A",
    descriptor: "Micro-embossed grain structure, consistent depth.",
    characteristics: [
      "Micro-embossed fine grain pattern",
      "Controlled surface depth",
      "Consistent emboss definition across roll",
      "Suitable for seat and trim surfaces",
      "Detailed specifications available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "bs-03",
    articleNumber: "SL-BS-03",
    name: "Black Dynamic",
    series: "Black Series",
    category: "Dynamic",
    surface: "Embossed",
    finish: "Gloss",
    pattern: "Geometric",
    color: "Black",
    swatch: "#222222",
    descriptor: "Geometric surface pattern with elevated visual contrast.",
    characteristics: [
      "Geometric emboss pattern",
      "Elevated gloss finish",
      "High visual contrast surface",
      "Suitable for decorative trim elements",
      "Sample sets available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "bs-04",
    articleNumber: "SL-BS-04",
    name: "Black Matte Structured",
    series: "Black Series",
    category: "Structured",
    surface: "Textured",
    finish: "Matte",
    pattern: "Structured",
    color: "Black",
    swatch: "#2A2A2A",
    descriptor: "Deep matte finish with anti-glare structured surface.",
    characteristics: [
      "Deep structured surface texture",
      "Anti-glare matte finish",
      "Controlled light diffusion",
      "Suitable for high-contact interior areas",
      "Technical datasheet available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "bs-05",
    articleNumber: "SL-BS-05",
    name: "Black Alcantara-Style",
    series: "Black Series",
    category: "Alcantara-Style",
    surface: "Microfiber",
    finish: "Matte",
    pattern: "Plain",
    color: "Black",
    swatch: "#181818",
    descriptor: "Microfiber-type surface with soft tactile texture.",
    characteristics: [
      "Soft microfiber surface character",
      "Low-gloss tactile finish",
      "Uniform nap direction",
      "Suitable for seat inserts and armrests",
      "Material samples available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&fit=crop",
    ],
  },

  // ─── BEIGE & SAND ────────────────────────────────────────────────
  {
    id: "be-01",
    articleNumber: "SL-BE-01",
    name: "Ivory Smooth",
    series: "Beige & Sand",
    category: "Smooth",
    surface: "Smooth",
    finish: "Satin",
    pattern: "Plain",
    color: "Beige",
    swatch: "#E8D5B0",
    descriptor: "Light cream base with smooth satin surface finish.",
    characteristics: [
      "Light cream surface tone",
      "Satin-finish surface",
      "Consistent colour across roll",
      "Suitable for premium seat and door surfaces",
      "Material samples available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "be-02",
    articleNumber: "SL-BE-02",
    name: "Sand Grain",
    series: "Beige & Sand",
    category: "Grain",
    surface: "Embossed",
    finish: "Matte",
    pattern: "Fine Grain",
    color: "Beige",
    swatch: "#D4BC8B",
    descriptor: "Warm sand tone with natural-look grain emboss.",
    characteristics: [
      "Warm sand base colour",
      "Natural grain emboss pattern",
      "Matte surface finish",
      "Suitable for seat and armrest surfaces",
      "Specifications available upon request",
    ],
    images: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "be-03",
    articleNumber: "SL-BE-03",
    name: "Cashmere Matte",
    series: "Beige & Sand",
    category: "Smooth",
    surface: "Smooth",
    finish: "Matte",
    pattern: "Plain",
    color: "Beige",
    swatch: "#C8B89A",
    descriptor: "Muted beige with low-sheen controlled surface.",
    characteristics: [
      "Muted neutral beige tone",
      "Low-sheen controlled surface",
      "Soft visual presence",
      "Suitable for refined interior applications",
      "Material samples available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "be-04",
    articleNumber: "SL-BE-04",
    name: "Warm Perforated",
    series: "Beige & Sand",
    category: "Perforated",
    surface: "Perforated",
    finish: "Matte",
    pattern: "Perforated",
    color: "Beige",
    swatch: "#C4A96E",
    descriptor: "Perforated sand surface, uniform hole distribution.",
    characteristics: [
      "Uniform micro-perforation pattern",
      "Warm sand base colour",
      "Consistent hole distribution",
      "Suitable for seat surfaces requiring ventilation",
      "Technical datasheet available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1616628182506-9d8f3f93b74b?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=90&fit=crop",
    ],
  },

  // ─── GREY COLLECTION ─────────────────────────────────────────────
  {
    id: "gr-01",
    articleNumber: "SL-GR-01",
    name: "Cool Silver",
    series: "Grey Collection",
    category: "Smooth",
    surface: "Smooth",
    finish: "Satin",
    pattern: "Plain",
    color: "Grey",
    swatch: "#9A9A9A",
    descriptor: "Light grey with subtle satin surface.",
    characteristics: [
      "Light grey surface tone",
      "Subtle satin finish",
      "Neutral cool undertone",
      "Suitable for seat and panel surfaces",
      "Samples available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "gr-02",
    articleNumber: "SL-GR-02",
    name: "Anthracite Grain",
    series: "Grey Collection",
    category: "Grain",
    surface: "Embossed",
    finish: "Matte",
    pattern: "Fine Grain",
    color: "Grey",
    swatch: "#525252",
    descriptor: "Mid-dark anthracite with structured grain pattern.",
    characteristics: [
      "Mid-dark anthracite tone",
      "Structured grain emboss",
      "Matte finish surface",
      "Suitable for seat and door panel materials",
      "Detailed specifications available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "gr-03",
    articleNumber: "SL-GR-03",
    name: "Slate Structured",
    series: "Grey Collection",
    category: "Structured",
    surface: "Textured",
    finish: "Matte",
    pattern: "Structured",
    color: "Grey",
    swatch: "#3A3A3A",
    descriptor: "Deep slate tone, uniform structured surface.",
    characteristics: [
      "Deep slate grey tone",
      "Uniform structured surface",
      "Matte finish",
      "Consistent texture across roll",
      "Sample sets available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "gr-04",
    articleNumber: "SL-GR-04",
    name: "Graphite Fine",
    series: "Grey Collection",
    category: "Grain",
    surface: "Embossed",
    finish: "Matte",
    pattern: "Fine Grain",
    color: "Grey",
    swatch: "#2E2E2E",
    descriptor: "Near-black graphite with micro-grain visibility.",
    characteristics: [
      "Near-black graphite tone",
      "Micro grain emboss pattern",
      "Subtle surface definition",
      "Suitable for premium trim elements",
      "Specifications available upon request",
    ],
    images: [
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90&fit=crop",
    ],
  },

  // ─── COGNAC & BROWN ──────────────────────────────────────────────
  {
    id: "co-01",
    articleNumber: "SL-CO-01",
    name: "Cognac Classic",
    series: "Cognac & Brown",
    category: "Grain",
    surface: "Embossed",
    finish: "Satin",
    pattern: "Fine Grain",
    color: "Brown",
    swatch: "#8B5A2B",
    descriptor: "Rich amber-brown with deep grain character.",
    characteristics: [
      "Rich amber-brown surface tone",
      "Deep grain emboss character",
      "Satin finish surface",
      "Suitable for premium seat and armrest applications",
      "Material samples available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "co-02",
    articleNumber: "SL-CO-02",
    name: "Tobacco Matte",
    series: "Cognac & Brown",
    category: "Smooth",
    surface: "Smooth",
    finish: "Matte",
    pattern: "Plain",
    color: "Brown",
    swatch: "#6B4226",
    descriptor: "Warm tobacco finish, low-reflectivity surface.",
    characteristics: [
      "Warm tobacco brown tone",
      "Low-reflectivity matte surface",
      "Consistent colour distribution",
      "Suitable for seat surfaces and door panels",
      "Datasheet available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "co-03",
    articleNumber: "SL-CO-03",
    name: "Cinnamon Grain",
    series: "Cognac & Brown",
    category: "Grain",
    surface: "Embossed",
    finish: "Matte",
    pattern: "Fine Grain",
    color: "Brown",
    swatch: "#A0522D",
    descriptor: "Medium brown with natural grain emboss.",
    characteristics: [
      "Medium cinnamon-brown tone",
      "Natural grain emboss pattern",
      "Matte finish",
      "Suitable for interior trim elements",
      "Samples available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1616628182506-9d8f3f93b74b?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "co-04",
    articleNumber: "SL-CO-04",
    name: "Dark Walnut",
    series: "Cognac & Brown",
    category: "Structured",
    surface: "Textured",
    finish: "Matte",
    pattern: "Structured",
    color: "Brown",
    swatch: "#4A2518",
    descriptor: "Deep brown tone, uniform surface consistency.",
    characteristics: [
      "Deep brown walnut tone",
      "Uniform structured surface",
      "Matte finish",
      "Consistent surface quality across roll",
      "Technical datasheet available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1616628182506-9d8f3f93b74b?w=1200&q=90&fit=crop",
    ],
  },

  // ─── PERFORMANCE RED ─────────────────────────────────────────────
  {
    id: "re-01",
    articleNumber: "SL-RE-01",
    name: "Sport Red",
    series: "Performance Red",
    category: "Smooth",
    surface: "Smooth",
    finish: "Gloss",
    pattern: "Plain",
    color: "Red",
    swatch: "#A52020",
    descriptor: "Saturated red with uniform surface sheen.",
    characteristics: [
      "Saturated red tone",
      "Uniform gloss surface",
      "Consistent colour density",
      "Suitable for accent trim and seat inserts",
      "Material samples available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "re-02",
    articleNumber: "SL-RE-02",
    name: "Dark Burgundy",
    series: "Performance Red",
    category: "Grain",
    surface: "Embossed",
    finish: "Matte",
    pattern: "Fine Grain",
    color: "Red",
    swatch: "#6B0F0F",
    descriptor: "Deep burgundy tone, grain surface character.",
    characteristics: [
      "Deep burgundy tone",
      "Fine grain emboss pattern",
      "Matte finish",
      "Suitable for seat and door panel materials",
      "Specifications available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "re-03",
    articleNumber: "SL-RE-03",
    name: "Crimson Structured",
    series: "Performance Red",
    category: "Structured",
    surface: "Textured",
    finish: "Gloss",
    pattern: "Structured",
    color: "Red",
    swatch: "#8B1A1A",
    descriptor: "Structured grain surface, high-density crimson finish.",
    characteristics: [
      "High-density structured surface",
      "Gloss finish",
      "Crimson red tone",
      "Suitable for contrast interior trim elements",
      "Datasheet and samples available on request",
    ],
    images: [
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=90&fit=crop",
    ],
  },

  // ─── OTHERS ──────────────────────────────────────────────────────
  {
    id: "ot-01",
    articleNumber: "SL-OT-01",
    name: "Custom Tone",
    series: "Others",
    category: "Smooth",
    surface: "Smooth",
    finish: "Matte",
    pattern: "Plain",
    color: "Custom",
    swatch: "#3A3A4A",
    descriptor: "Available upon request — specify RAL or Pantone reference.",
    characteristics: [
      "Custom colour matching available",
      "RAL or Pantone reference accepted",
      "Surface type selectable from standard range",
      "Minimum order quantities apply",
      "Contact us for specification and lead time",
    ],
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "ot-02",
    articleNumber: "SL-OT-02",
    name: "Special Edition",
    series: "Others",
    category: "Grain",
    surface: "Embossed",
    finish: "Satin",
    pattern: "Fine Grain",
    color: "Custom",
    swatch: "#2E2E2E",
    descriptor: "Limited production runs for specific project requirements.",
    characteristics: [
      "Limited production availability",
      "Project-specific colour and texture",
      "Suitable for custom interior projects",
      "Minimum order quantities apply",
      "Enquire for availability and specifications",
    ],
    images: [
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&fit=crop",
    ],
  },
  {
    id: "ot-03",
    articleNumber: "SL-OT-03",
    name: "Non-Standard Shade",
    series: "Others",
    category: "Structured",
    surface: "Textured",
    finish: "Matte",
    pattern: "Structured",
    color: "Custom",
    swatch: "#4A4040",
    descriptor: "Material samples and specifications available upon request.",
    characteristics: [
      "Non-standard colour range",
      "Surface options available on request",
      "Suitable for specialist project requirements",
      "Minimum order quantities apply",
      "Contact us with your specification",
    ],
    images: [
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1200&q=90&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90&fit=crop",
    ],
  },
];

export const SERIES = [...new Set(variants.map((v) => v.series))];
export const COLORS = [...new Set(variants.map((v) => v.color))];
export const CATEGORIES = [...new Set(variants.map((v) => v.category))];
export const SURFACES = [...new Set(variants.map((v) => v.surface))];
export const FINISHES = [...new Set(variants.map((v) => v.finish))];
export const PATTERNS = [...new Set(variants.map((v) => v.pattern))];
